name: Script PHP Workflow

on:
  workflow_dispatch:

jobs:
  script-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run PHP Script
        run: php index.php

      - name: Print Message
        run: echo "Script Workflow Completed"