name: Manual Workflow

on: 
  workflow_dispatch:

jobs:
  manual-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: First manual step
        run: |
          echo "Hello, from Manual Workflow!"
          echo "Hello again from Manual Workflow!"