name: Cronjob Workflow

on: 
  schedule:
    - cron: '*/5 * * * *'  # Runs in every 5 minutes

jobs:
  cron-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cron workflow
        run: |
          echo "Hello, Cron Job!"