name: Multi Job Workflow

on: 
  workflow_dispatch:

jobs:
  first-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: First Workflow Job
        run: |
          echo "Hello, First Workflow!"

  second-workflow-job:
    runs-on: ubuntu-latest

    steps:
      - name: Second Workflow Job
        run: |
          echo "Hello, Second Workflow!"